# Supabase
spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=${SUPABASE_USER}
spring.datasource.password=${SUPABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-postgres.sql
spring.jpa.defer-datasource-initialization=true

# Desactivar consola H2 en este perfil
spring.h2.console.enabled=false