spring.application.name=watts2crypto-backend

# H2 en modo fichero (persiste entre reinicios)
spring.datasource.url=jdbc:h2:file:./data/watts2crypto
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 (accesible en http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Inyeccion de variables de entorno
spring.config.import=optional:file:.env[.properties]

